export const countryCodes = {
  'Australia [AUS]': 'AU',
  'India [IND]': 'IN',
  'Pakistan [PAK]': 'PK',
  'South Africa [RSA]': 'ZA',
  'New Zealand [NZ]': 'NZ',
  'England [ENG]': 'GB',
  'Sri Lanka [SL]': 'LK',
  'West Indies [WI]': 'JM', // Jamaica (as a representative country for WI)
  'Bangladesh [BAN]': 'BD',
  'Afghanistan [AFG]': 'AF',
  'Zimbabwe [ZIM]': 'ZW',
  'Ireland [IRE]': 'IE',
  'Scotland [SCO]': 'GB', // Scotland as part of the UK
  'Netherlands [NED]': 'NL',
  'United Arab Emirates [UAE]': 'AE',
  'Nepal [NEP]': 'NP',
  'Hong Kong [HK]': 'HK',
  'Oman [OMN]': 'OM',
  'Canada [CAN]': 'CA',
  'USA [USA]': 'US',
    //Other Teams
  'New Zealand Xi [NZXI]': 'NZ',
  'Indonesia [IDN]': 'ID',
  'Myanmar [MYAN]': 'MM',
  'Pakistan A [PKA]': 'PK',
  'Sri Lanka A [SLA]': 'LK',
  'Nigeria [NGA]': 'NG',
  // Additional countries
  'Malaysia [MAS]': 'MY',
  'Singapore [SIN]': 'SG',
  'Kuwait [KUW]': 'KW',
  'Bermuda [BER]': 'BM',
  'Papua New Guinea [PNG]': 'PG',
  'Namibia [NAM]': 'NA',
  'Botswana [BOT]': 'BW',
  'Kenya [KEN]': 'KE',
  'Uganda [UGA]': 'UG',
  'Tanzania [TAN]': 'TZ',
  'Saudi Arabia [KSA]': 'SA',
  'Qatar [QAT]': 'QA',
  'Germany [GER]': 'DE',
  'Italy [ITA]': 'IT',
  'Spain [ESP]': 'ES',
  'Portugal [POR]': 'PT',
  'France [FRA]': 'FR',
  'Belgium [BEL]': 'BE',
  'Switzerland [SUI]': 'CH',
  'Denmark [DEN]': 'DK',
  'Norway [NOR]': 'NO',
  'Sweden [SWE]': 'SE',
  'Austria [AUT]': 'AT',
  'Czech Republic [CZE]': 'CZ',
  'Finland [FIN]': 'FI',
  'Greece [GRE]': 'GR',
  'Cyprus [CYP]': 'CY',
  'Israel [ISR]': 'IL',
  'Japan [JPN]': 'JP',
  'South Korea [KOR]': 'KR',
  'Thailand [THA]': 'TH',
  'Indonesia [INA]': 'ID',
  'China [CHN]': 'CN',
  'Philippines [PHI]': 'PH',

  };
  