const members = [
  {
    _id: "hdjsjjsjs",
    firstName: "Mrinal",
    lastName: "Anand",
    type: "User",
    role: "Athlete",
    profilePic: "",
  },
  {
    _id: "hdjsjjsjs637838383",
    firstName: "Anirban",
    lastName: "Dutta",
    type: "User",
    role: "Coach",
    profilePic: "",
  },
  {
    _id: "hdjsjjsjs63dkksks7838383",
    firstName: "Anirban",
    lastName: "Dutta",
    type: "User",
    role: "Coach",
    profilePic: "",
  },
  {
    _id: "hdjsjjsjs6378387s63hns383",
    firstName: "Anirban",
    lastName: "Dutta",
    type: "User",
    role: "Coach",
    profilePic: "",
  },
  {
    _id: "hdjsjjsjs63782723bdnd38383",
    firstName: "Anirban",
    lastName: "Dutta",
    type: "User",
    role: "Coach",
    profilePic: "",
  },
  {
    _id: "hdjsjjsjs6378sljvvjkvskv38383",
    firstName: "Anirban",
    lastName: "Dutta",
    type: "User",
    role: "Coach",
    profilePic: "",
  },
  {
    _id: "hdjsjjsjs637853535353538383",
    firstName: "Anirban",
    lastName: "Dutta",
    type: "User",
    role: "Coach",
    profilePic: "",
  },
];
export default members;
