export const countryAbbreviations: { [key: string]: string } = {
  "United Arab Emirates": "UAE",
  "United States of America": "USA",
  "United States": "USA",
  "United Kingdom": "UK",
  "Antigua and Barbuda": "ATG",
  "Bosnia and Herzegovina": "BIH",
  "British Virgin Islands": "VGB",
  "Cayman Islands": "CYM",
  "Central African Republic": "CAF",
  "Cook Islands": "COK",
  "Costa Rica": "CRI",
  "Czech Republic": "CZE",
  "Dominican Republic": "DOM",
  "El Salvador": "SLV",
  "Equatorial Guinea": "GNQ",
  "Falkland Islands": "FLK",
  "Faroe Islands": "FRO",
  "French Polynesia": "PYF",
  "Marshall Islands": "MHL",
  "New Caledonia": "NCL",
  "New Zealand": "NZL",
  "North Macedonia": "MKD",
  "Papua New Guinea": "PNG",
  "Puerto Rico": "PRI",
  "Saint Kitts and Nevis": "KNA",
  "Saint Lucia": "LCA",
  "Saint Vincent and the Grenadines": "VCT",
  "San Marino": "SMR",
  "Sao Tome and Principe": "STP",
  "Saudi Arabia": "SAU",
  "Sierra Leone": "SLE",
  "Solomon Islands": "SLB",
  "South Africa": "ZAF",
  "South Korea": "KOR",
  "Sri Lanka": "LKA",
  "Trinidad and Tobago": "TTO",
  "Turks and Caicos Islands": "TCA",
  "Vatican City": "VAT",
  "Democratic Republic of the Congo": "COD",
  "Republic of the Congo": "COG",
  "United States Minor Outlying Islands": "UMI",
  "Northern Mariana Islands": "MNP",
  "Saint Helena, Ascension and Tristan da Cunha": "SHN",
  "Svalbard and Jan Mayen": "SJM",
  "Timor-Leste": "TLS",
  "Virgin Islands, British": "VGB",
  "Virgin Islands, U.S.": "VIR",
  "Wallis and Futuna": "WLF",
  "Western Sahara": "ESH",
  "Bouvet Island": "BVT",
  "Heard Island and McDonald Islands": "HMD",
  "British Indian Ocean Territory": "IOT",
  "Federated States of Micronesia": "FSM",
  "Saint Pierre and Miquelon": "SPM",
  "American Samoa": "ASM",
  "French Southern Territories": "ATF",
  "Isle of Man": "IMN",
  "Norfolk Island": "NFK",
  "Pitcairn Islands": "PCN",
  "South Georgia and the South Sandwich Islands": "SGS",
  "Lao People's Democratic Republic": "LAO",
  "Democratic People's Republic of Korea": "PRK",
  "Republic of Korea": "KOR",
  "Russian Federation": "RUS",
  "Syrian Arab Republic": "SYR",
  "United Republic of Tanzania": "TZA",
  "Bolivarian Republic of Venezuela": "VEN",
  Australia: "AUS",
  Afghanistan: "AFG",
  Argentina: "ARG",
  Bangladesh: "BGD",
  Cambodia: "KHM",
  Colombia: "COL",
  Ethiopia: "ETH",
  Indonesia: "IDN",
  Madagascar: "MDG",
  Mozambique: "MOZ",
  Philippines: "PHL",
  Switzerland: "CHE",
  Luxembourg: "LUX",
  Mauritania: "MRT",
  Mauritius: "MUS",
  Nicaragua: "NIC",
  Paraguay: "PRY",
  Singapore: "SGP",
  Slovakia: "SVK",
  Slovenia: "SVN",
  Tajikistan: "TJK",
  Turkmenistan: "TKM",
  Uzbekistan: "UZB",
  Uruguay: "URY",
  Netherlands: "NLD",
  "Aland Islands": "ALA",
  Albania: "ALB",
  Algeria: "DZA",
  Andorra: "AND",
  Anguilla: "AIA",
  Armenia: "ARM",
  Austria: "AUT",
  Azerbaijan: "AZE",
  Bahamas: "BHS",
  Bahrain: "BHR",
  Barbados: "BRB",
  Belarus: "BLR",
  Belgium: "BEL",
  Bermuda: "BMU",
  Bolivia: "BOL",
  Botswana: "BWA",
  "Brunei Darussalam": "BRN",
  Bulgaria: "BGR",
  "Burkina Faso": "BFA",
  Burundi: "BDI",
  "Cabo Verde": "CPV",
  Cameroon: "CMR",
  "Christmas Island": "CXR",
  "Cocos (Keeling) Islands": "CCK",
  Comoros: "COM",
  Croatia: "HRV",
  Curacao: "CUW",
  Czechia: "CZE",
  Denmark: "DNK",
  Djibouti: "DJI",
  Ecuador: "ECU",
  Eritrea: "ERI",
  Estonia: "EST",
  Eswatini: "SWZ",
  Finland: "FIN",
  Georgia: "GEO",
  Germany: "DEU",
  Gibraltar: "GIB",
  Greenland: "GRL",
  Grenada: "GRD",
  Guadeloupe: "GLP",
  Guatemala: "GTM",
  Guernsey: "GGY",
  "Guinea-Bissau": "GNB",
  Honduras: "HND",
  "Hong Kong": "HKG",
  Hungary: "HUN",
  Iceland: "ISL",
  Ireland: "IRL",
  Jamaica: "JAM",
  Kazakhstan: "KAZ",
  Kiribati: "KIR",
  Kyrgyzstan: "KGZ",
  Lebanon: "LBN",
  Lesotho: "LSO",
  Liberia: "LBR",
  Liechtenstein: "LIE",
  Lithuania: "LTU",
  Malaysia: "MYS",
  Maldives: "MDV",
  Martinique: "MTQ",
  Mayotte: "MYT",
  Moldova: "MDA",
  Mongolia: "MNG",
  Montenegro: "MNE",
  Montserrat: "MSR",
  Morocco: "MAR",
  Myanmar: "MMR",
  Namibia: "NAM",
  Nigeria: "NGA",
  Pakistan: "PAK",
  "Palestine, State of": "PSE",
  Portugal: "PRT",
  Reunion: "REU",
  Romania: "ROU",
  Senegal: "SEN",
  Seychelles: "SYC",
  "Sint Maarten (Dutch part)": "SXM",
  Somalia: "SOM",
  "South Sudan": "SSD",
  Suriname: "SUR",
  Thailand: "THA",
  Tokelau: "TKL",
  Tunisia: "TUN",
  Türkiye: "TUR",
  Ukraine: "UKR",
  Vanuatu: "VUT",
  Vietnam: "VNM",
  Zimbabwe: "ZWE",
};